{
 "title": "example-hpa",
 "description": "Number of requests and bytes size by server zone and backend service",
 "tags": [
  "k8s",
  "kubernetes",
  "ingress",
  "nginx",
  "stats"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\",pod_name=~\"example-hpa.*\"}[30s])) by (name,instance)",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "- rate(container_network_transmit_bytes_total{name=~\".+\",pod_name=~\"example-hpa.*\"}[30s])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "replicas",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(container_last_seen{name=~\".+\",job=\"cadvisor\",namespace=\"moonitoring\",pod_name=~\"example-hpa.*\"}) / 2"
    }
   ]
  },
  {
   "title": "Requests / sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_ingress_controller_requests{exported_namespace=\"moonitoring\",ingress=\"example-hpa-ingress\"}[1m])",
     "legendFormat": "{{ingress}} - {{status}}"
    }
   ]
  }
 ]
}